### ISSUE TITLE
Login evaluador

### ISSUE THREAD

**Issue by alexfuser** [CodeandoMexico/APAC#2]
<img width="441" alt="1_login_evaluador" src="https://user-images.githubusercontent.com/1179211/47037845-a66e5f80-d145-11e8-9d75-f1e86ca02cc7.png">

**Comment by toshitapandey** [comment]
@alexfuser does this mean, you want HTML CSS for this snippet?

**Comment by alexfuser** [comment]
@toshitapandey Yes but the project is in Angular. It has to be in a component.
